# Generated by Django 5.1.1 on 2024-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='sent_at',
        ),
    ]
