# Generated by Django 5.0.6 on 2024-09-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='read_at',
        ),
    ]
