# Generated by Django 5.0.6 on 2024-09-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_remove_inbox_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
