# Generated by Django 5.0.6 on 2024-08-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='short_description',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
