# Generated by Django 5.1.1 on 2024-09-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
