# Generated by Django 5.1.1 on 2024-09-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_is_complete_todo_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
