# Generated by Django 5.1.1 on 2024-09-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todo_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_trashed',
        ),
    ]
